// flow-typed signature: 23fdc9b480bca98a2ec1c79cdab25d81
// flow-typed version: <<STUB>>/canvas-prebuilt_v^1.6.5-prerelease.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canvas-prebuilt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canvas-prebuilt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canvas-prebuilt/canvas/index' {
  declare module.exports: any;
}

declare module 'canvas-prebuilt/canvas/lib/bindings' {
  declare module.exports: any;
}

declare module 'canvas-prebuilt/canvas/lib/canvas' {
  declare module.exports: any;
}

declare module 'canvas-prebuilt/canvas/lib/context2d' {
  declare module.exports: any;
}

declare module 'canvas-prebuilt/canvas/lib/image' {
  declare module.exports: any;
}

declare module 'canvas-prebuilt/canvas/lib/jpegstream' {
  declare module.exports: any;
}

declare module 'canvas-prebuilt/canvas/lib/pdfstream' {
  declare module.exports: any;
}

declare module 'canvas-prebuilt/canvas/lib/pngstream' {
  declare module.exports: any;
}

declare module 'canvas-prebuilt/ci/release' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canvas-prebuilt/canvas/index.js' {
  declare module.exports: $Exports<'canvas-prebuilt/canvas/index'>;
}
declare module 'canvas-prebuilt/canvas/lib/bindings.js' {
  declare module.exports: $Exports<'canvas-prebuilt/canvas/lib/bindings'>;
}
declare module 'canvas-prebuilt/canvas/lib/canvas.js' {
  declare module.exports: $Exports<'canvas-prebuilt/canvas/lib/canvas'>;
}
declare module 'canvas-prebuilt/canvas/lib/context2d.js' {
  declare module.exports: $Exports<'canvas-prebuilt/canvas/lib/context2d'>;
}
declare module 'canvas-prebuilt/canvas/lib/image.js' {
  declare module.exports: $Exports<'canvas-prebuilt/canvas/lib/image'>;
}
declare module 'canvas-prebuilt/canvas/lib/jpegstream.js' {
  declare module.exports: $Exports<'canvas-prebuilt/canvas/lib/jpegstream'>;
}
declare module 'canvas-prebuilt/canvas/lib/pdfstream.js' {
  declare module.exports: $Exports<'canvas-prebuilt/canvas/lib/pdfstream'>;
}
declare module 'canvas-prebuilt/canvas/lib/pngstream.js' {
  declare module.exports: $Exports<'canvas-prebuilt/canvas/lib/pngstream'>;
}
declare module 'canvas-prebuilt/ci/release.js' {
  declare module.exports: $Exports<'canvas-prebuilt/ci/release'>;
}
