// flow-typed signature: 8753f15484a578fad77f8a778884135d
// flow-typed version: <<STUB>>/check-prop-types_v^1.1.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'check-prop-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'check-prop-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'check-prop-types/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'check-prop-types/index' {
  declare module.exports: $Exports<'check-prop-types'>;
}
declare module 'check-prop-types/index.js' {
  declare module.exports: $Exports<'check-prop-types'>;
}
declare module 'check-prop-types/test.js' {
  declare module.exports: $Exports<'check-prop-types/test'>;
}
