// flow-typed signature: abd8e6fc5f40c8af1c8bd3b822a3df59
// flow-typed version: <<STUB>>/eslint-config-react-native_v^2.0.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-react-native' {
  declare module.exports: any;
}
