// flow-typed signature: 1af709c0ff76f41b57ee632c818e25eb
// flow-typed version: <<STUB>>/@skpm/builder_vfile:../skpm/packages/builder/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@skpm/builder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@skpm/builder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@skpm/builder/lib/build' {
  declare module.exports: any;
}

declare module '@skpm/builder/lib/link' {
  declare module.exports: any;
}

declare module '@skpm/builder/lib/utils/babelLoader' {
  declare module.exports: any;
}

declare module '@skpm/builder/lib/utils/resourceLoader' {
  declare module.exports: any;
}

declare module '@skpm/builder/lib/utils/webpackCommandPlugin/index' {
  declare module.exports: any;
}

declare module '@skpm/builder/lib/utils/webpackCommandPlugin/sketchCommandPlugin' {
  declare module.exports: any;
}

declare module '@skpm/builder/lib/utils/webpackCommandPlugin/webpackShellPlugin' {
  declare module.exports: any;
}

declare module '@skpm/builder/lib/utils/webpackConfig' {
  declare module.exports: any;
}

declare module '@skpm/builder/lib/utils/webpackHeaderFooterPlugin' {
  declare module.exports: any;
}

declare module '@skpm/builder/src/build' {
  declare module.exports: any;
}

declare module '@skpm/builder/src/link' {
  declare module.exports: any;
}

declare module '@skpm/builder/src/utils/babelLoader' {
  declare module.exports: any;
}

declare module '@skpm/builder/src/utils/resourceLoader' {
  declare module.exports: any;
}

declare module '@skpm/builder/src/utils/webpackCommandPlugin/index' {
  declare module.exports: any;
}

declare module '@skpm/builder/src/utils/webpackCommandPlugin/sketchCommandPlugin' {
  declare module.exports: any;
}

declare module '@skpm/builder/src/utils/webpackCommandPlugin/webpackShellPlugin' {
  declare module.exports: any;
}

declare module '@skpm/builder/src/utils/webpackConfig' {
  declare module.exports: any;
}

declare module '@skpm/builder/src/utils/webpackHeaderFooterPlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module '@skpm/builder/lib/build.js' {
  declare module.exports: $Exports<'@skpm/builder/lib/build'>;
}
declare module '@skpm/builder/lib/link.js' {
  declare module.exports: $Exports<'@skpm/builder/lib/link'>;
}
declare module '@skpm/builder/lib/utils/babelLoader.js' {
  declare module.exports: $Exports<'@skpm/builder/lib/utils/babelLoader'>;
}
declare module '@skpm/builder/lib/utils/resourceLoader.js' {
  declare module.exports: $Exports<'@skpm/builder/lib/utils/resourceLoader'>;
}
declare module '@skpm/builder/lib/utils/webpackCommandPlugin/index.js' {
  declare module.exports: $Exports<'@skpm/builder/lib/utils/webpackCommandPlugin/index'>;
}
declare module '@skpm/builder/lib/utils/webpackCommandPlugin/sketchCommandPlugin.js' {
  declare module.exports: $Exports<'@skpm/builder/lib/utils/webpackCommandPlugin/sketchCommandPlugin'>;
}
declare module '@skpm/builder/lib/utils/webpackCommandPlugin/webpackShellPlugin.js' {
  declare module.exports: $Exports<'@skpm/builder/lib/utils/webpackCommandPlugin/webpackShellPlugin'>;
}
declare module '@skpm/builder/lib/utils/webpackConfig.js' {
  declare module.exports: $Exports<'@skpm/builder/lib/utils/webpackConfig'>;
}
declare module '@skpm/builder/lib/utils/webpackHeaderFooterPlugin.js' {
  declare module.exports: $Exports<'@skpm/builder/lib/utils/webpackHeaderFooterPlugin'>;
}
declare module '@skpm/builder/src/build.js' {
  declare module.exports: $Exports<'@skpm/builder/src/build'>;
}
declare module '@skpm/builder/src/link.js' {
  declare module.exports: $Exports<'@skpm/builder/src/link'>;
}
declare module '@skpm/builder/src/utils/babelLoader.js' {
  declare module.exports: $Exports<'@skpm/builder/src/utils/babelLoader'>;
}
declare module '@skpm/builder/src/utils/resourceLoader.js' {
  declare module.exports: $Exports<'@skpm/builder/src/utils/resourceLoader'>;
}
declare module '@skpm/builder/src/utils/webpackCommandPlugin/index.js' {
  declare module.exports: $Exports<'@skpm/builder/src/utils/webpackCommandPlugin/index'>;
}
declare module '@skpm/builder/src/utils/webpackCommandPlugin/sketchCommandPlugin.js' {
  declare module.exports: $Exports<'@skpm/builder/src/utils/webpackCommandPlugin/sketchCommandPlugin'>;
}
declare module '@skpm/builder/src/utils/webpackCommandPlugin/webpackShellPlugin.js' {
  declare module.exports: $Exports<'@skpm/builder/src/utils/webpackCommandPlugin/webpackShellPlugin'>;
}
declare module '@skpm/builder/src/utils/webpackConfig.js' {
  declare module.exports: $Exports<'@skpm/builder/src/utils/webpackConfig'>;
}
declare module '@skpm/builder/src/utils/webpackHeaderFooterPlugin.js' {
  declare module.exports: $Exports<'@skpm/builder/src/utils/webpackHeaderFooterPlugin'>;
}
